sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION rootJS/scalastyle testSuiteJVM/scalastyle testSuiteJVM/test:scalastyle testSuiteJS/scalastyle testSuiteJS/test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION testSuiteJVM/test
  - sbt ++$TRAVIS_SCALA_VERSION testSuiteJS/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set scalaJSStage in Global := FullOptStage' testSuiteJS/test
  - sbt ++$TRAVIS_SCALA_VERSION rootJS/publishLocal
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.10
  - 2.13.1
jdk:
  - openjdk8
env:
  - SCALAJS_VERSION=0.6.29
  - SCALAJS_VERSION=1.0.0-M8
matrix:
  exclude:
    - scala: 2.10.7
      env: SCALAJS_VERSION=1.0.0-M8
  include:
    - scala: 2.11.12
      jdk: openjdk8
      env:
      - SCALA_NATIVE_VERSION="0.3.9"
      sudo: required
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -
      script:
      - sbt "++$TRAVIS_SCALA_VERSION!" nativeTestSuite/test rootNative/publishLocal
    - scala: 2.11.12
      jdk: openjdk8
      env:
      - SCALA_NATIVE_VERSION="0.4.0-M2"
      sudo: required
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -
      script:
      - sbt "++$TRAVIS_SCALA_VERSION!" nativeTestSuite/test rootNative/publishLocal
  cache:
  directories:
    - "$HOME/.cache/coursier/v1"
    - "$HOME/.sbt"
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.coursier -name "*.lock" | xargs rm
  - find $HOME/.sbt -name "*.lock" -print -delete
